[mysql]
host = "serverless-us-east4.sysp0000.db2.skysql.com"
port = 4069
database = "mydatabase"       # check exact database name in SkySQL!
user = "dbpgf02950067"
password = "MyNewSecurePassword123!"
